### ISSUE TITLE
Page level 2 is not visible in the page management

### ISSUE THREAD

**Issue by VeNick-GS** [risingisland/GetSimpleCMS-CE-3.3.19.1#4]
Hi @risingisland 

New bag was found with page management.
When I create 2 level page like:
![Nav_structure](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/75deca3e-25d5-475e-a119-f21c99405fec)

then DropDown1 page is not visible on the Page management:
![Page_management](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/7d097c62-83b5-4bec-9ee6-46709e151f51)

Button "Show all pages" open it but shows not correctly:
![Page_management_2](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/60d22d5d-a880-4136-8b19-aa9ba70c48c9)

After changing an order of parent pages:
  
![Page_management_3](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/f2251c82-7346-4770-b26e-61c5c1948c5a)

page DropDown1 is visible:
![Page_management_4](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/64dfab76-9957-45c0-a8c1-3f3728fbb8e8)

I have tested the same example with GS CE 3.3.18.1 - there is no such bug.

**Comment by risingisland** [comment]
OK, I will take a look at this soon.
As a favor, to make this easier, please let me know what plugins you are using.
I didnt realize you were using i18n menu and couldnt figure out why everything was different.
Try this first to see if this fixes it:
In gsconfig.php, in front of line 46 add a "#" in front of "define('GSSORTPAGELISTBY','menu'); "
and tell me if this fixes problem.

**Comment by VeNick-GS** [comment]
Line 46 doesn't help.
I use 2 langs.
Plugins used:
![plugins](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/675923fb-186e-4797-a3eb-26410baf3f99)

**The bug is only when I add Page 3:**
![plugins_2](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/da9564ec-043f-4f83-a6db-2d9374c1e82c)
![plugins_3](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/78678788/7a4d5494-a9d4-4f68-bd0e-bc27856ee664)

The same problem with versions 3.3.19 and 3.3.18.1 on PHP 7.4.8. 
With PHP 8.1 there are no problems.

Version 3.3.16 on PHP 7.4.8 is OK.

**Comment by risingisland** [comment]
So, just to understand, this problem is only x.18-.19 on php7.4.
Both work fine on 8.1. 
Is that correct?

I actually didnt know 3.3.16 worked on PHP 7.4. I dont think I tried it :) 

I thought it might have been because of recent update I did, but it sounds like is an existing bug in the plugin if it was also a problem in the x.18 version.
I will pass this over to @multicolor-rgb to see if he has any ideas.

**Comment by VeNick-GS** [comment]
Correct.

Core 3.3.16 with latest i18n plugins is working on PHP 7.4

**Comment by risingisland** [comment]
OK, so, I have been trying to re-create this issue, but can not.
I have created this structure, at it works for me on both 7.4 and 8.1
![image](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/6113504/d41d9a0f-f355-48ff-9015-69afc11b75cb)
So, I am not sure what is going on.
I will have Multi take a look and see if he can reproduce this error.

**Comment by risingisland** [comment]
The version of i18n you are using is from the CE repo or GS website?
I think they are the same, but just checking.

**Comment by VeNick-GS** [comment]
I use i18n installed with CE downloader plugin and I tested with three different installations with the same bug.
Please try to test with two language pages - I think the problem is there.

**Comment by risingisland** [comment]
OK, will give that a try and see if that is the problem. Will let you know as soon as I find something.

**Comment by multicolor-rgb** [comment]
![proof](https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/assets/83913997/b24b4bca-183e-44a3-a514-b70c3702cc59)
Hi! Problem is not our CE version but style on i18n base. I fixed this, soon on repo. Now on download here:
https://github.com/multicolor-rgb/i18n-navigation---i18n-base-CE-edit

**Comment by VeNick-GS** [comment]
Hi @multicolor-rgb 
Reinstallation of plugins did not fix the problem.
Only after full reinstallation of GS and new installation of the plugins this problem was solved! 
Thank you for great job!

**Comment by risingisland** [comment]
Probably a cache problem would be my guess.
ctrl+F5 to force refresh, or try opening in private/incognito mode to check.
Glad this fix did the job!

**Comment by VeNick-GS** [comment]
Cleaning the cache and ctrl+F5 did not help.
But any way bug is fixed!
Thank you!
